[build]
  command = "npm run build"
  publish = "dist/task-management-system.ui"

[build.environment]
  BACKEND_URL = "https://taskmanagement-dkgy.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200