[build]
  command = "ng build --configuration production"
  publish = "dist/task-management-system.ui"

[build.environment]
  BACKEND_URL = "https://taskmanagement-dkgy.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404