[build]
  command = "npm run build"
  publish = "dist/TaskManagementSystem"

[build.environment]
  BACKEND_URL = "https://taskmanagement-dkgy.onrender.com/api"

[[plugins]]
  package = "@netlify/plugin-angular-universal"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200